{
 "title": "SLIs",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Kafka pods ready",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_status_ready{namespace=\"kafka-cluster\", condition=\"true\", pod=~\".*kafka.*\"}"
    }
   ]
  },
  {
   "title": "Kafka pods ready",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_ready{namespace=\"kafka-cluster\", condition=\"true\", pod=~\".*kafka.*\"}"
    }
   ]
  },
  {
   "title": "Zookeeper pods ready",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_status_ready{namespace=\"kafka-cluster\", condition=\"true\", pod=~\".*zookeeper.*\"}"
    }
   ]
  },
  {
   "title": "Zookeeper pods ready",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_ready{namespace=\"kafka-cluster\", condition=\"true\", pod=~\".*zookeeper.*\"}"
    }
   ]
  },
  {
   "title": "Partitions at min ISR",
   "type": "singlestat",
   "description": "Partitions at min ISR is a kind of warning that if one more replica falls behind and is out of sync, the producers won’t be able to send to those partitions with acks = all anymore.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_atminisr{partition=\"0\"})"
    }
   ]
  },
  {
   "title": "Partitions at min ISR",
   "type": "graph",
   "description": "Partitions at min ISR is a kind of warning that if one more replica falls behind and is out of sync, the producers won’t be able to send to those partitions with acks = all anymore.",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_atminisr{partition=\"0\"})"
    }
   ]
  },
  {
   "title": "Partitions under min ISR",
   "type": "singlestat",
   "description": "Partitions under min ISR don’t allow the producers to send to those partitions with acks = all anymore.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{partition=\"0\"})"
    }
   ]
  },
  {
   "title": "Partitions under min ISR",
   "type": "graph",
   "description": "Partitions under min ISR don’t allow the producers to send to those partitions with acks = all anymore.",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{partition=\"0\"})"
    }
   ]
  },
  {
   "title": "Under-replicated Partitions",
   "type": "singlestat",
   "description": "In a healthy cluster, the number of ISR (In-Sync Replicas) should be equal to the number of total replicas. When a follower replica falls behind the leader (so actually having not all messages), at some point it is removed from the ISR. It means that the partition is “under replicated” (not having enough replicas) and it could cause problems in HA. Producers can still send (with acks = all) if the number of ISR is stil >= min ISR.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions)"
    }
   ]
  },
  {
   "title": "Under-replicated Partitions",
   "type": "graph",
   "description": "In a healthy cluster, the number of ISR (In-Sync Replicas) should be equal to the number of total replicas. When a follower replica falls behind the leader (so actually having not all messages), at some point it is removed from the ISR. It means that the partition is “under replicated” (not having enough replicas) and it could cause problems in HA. Producers can still send (with acks = all) if the number of ISR is stil >= min ISR.",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions)"
    }
   ]
  },
  {
   "title": "Active controller",
   "type": "singlestat",
   "description": "Active Controller count defines the number of active controllers in the Kafka cluster that HAS TO BE always 1. Not having an active controller means not a functional cluster because it handles/coordinates different operations like leadership transitions and so on.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "Active controller",
   "type": "graph",
   "description": "Active Controller count defines the number of active controllers in the Kafka cluster that HAS TO BE always 1. Not having an active controller means not a functional cluster because it handles/coordinates different operations like leadership transitions and so on.",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "Kafka - Quality - Partitions Online",
   "type": "singlestat",
   "description": "Offline partitions so the number of partitions without an active leader which means not usable partitions because read/write goes through this (that is in general, in latest versions consumers are able to read from closed replicas based on rack-awareness).",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 30 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - sum(sum_over_time(kafka_controller_kafkacontroller_offlinepartitionscount[7d])) / sum(sum_over_time(kafka_controller_kafkacontroller_globalpartitioncount[7d]))"
    }
   ]
  },
  {
   "title": "Kafka - Quality - Partitions Online",
   "type": "graph",
   "description": "Offline partitions so the number of partitions without an active leader which means not usable partitions because read/write goes through this (that is in general, in latest versions consumers are able to read from closed replicas based on rack-awareness).",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - sum(sum_over_time(kafka_controller_kafkacontroller_offlinepartitionscount[7d])) / sum(sum_over_time(kafka_controller_kafkacontroller_globalpartitioncount[7d]))"
    }
   ]
  },
  {
   "title": "Kafka - Latency - 95% of producer requests < x ms",
   "type": "singlestat",
   "description": "Define the latency for main protocol requests sent by producer and consumer, even if they are heavily influenced by how the clients are configured (i.e. producer “acks”).",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 35 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_network_requestmetrics_totaltimems{quantile=\"0.95\", request=\"Produce\"})"
    }
   ]
  },
  {
   "title": "Kafka - Latency - 95% of producer requests < x ms",
   "type": "graph",
   "description": "Define the latency for main protocol requests sent by producer and consumer, even if they are heavily influenced by how the clients are configured (i.e. producer “acks”).",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kafka_network_requestmetrics_totaltimems{quantile=\"0.95\", request=\"Produce\"})"
    }
   ]
  },
  {
   "title": "Kafka - Latency - 95% of fetch consumer requests < x ms",
   "type": "singlestat",
   "description": "Define the latency for main protocol requests sent by producer and consumer, even if they are heavily influenced by how the clients are configured (i.e. producer “acks”).",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 40 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_network_requestmetrics_totaltimems{quantile=\"0.95\", request=\"FetchConsumer\"})"
    }
   ]
  },
  {
   "title": "Kafka - Latency - 95% of fetch consumer requests < x ms",
   "type": "graph",
   "description": "Define the latency for main protocol requests sent by producer and consumer, even if they are heavily influenced by how the clients are configured (i.e. producer “acks”).",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kafka_network_requestmetrics_totaltimems{quantile=\"0.95\", request=\"FetchConsumer\"})"
    }
   ]
  },
  {
   "title": "Kafka - Latency - 95% of fetch follower requests < x ms",
   "type": "singlestat",
   "description": "Define the latency for main protocol requests sent by producer and consumer, even if they are heavily influenced by how the clients are configured (i.e. producer “acks”).",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 45 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_network_requestmetrics_totaltimems{quantile=\"0.95\", request=\"FetchFollower\"})"
    }
   ]
  },
  {
   "title": "Kafka - Latency - 95% of fetch follower requests < x ms",
   "type": "graph",
   "description": "Define the latency for main protocol requests sent by producer and consumer, even if they are heavily influenced by how the clients are configured (i.e. producer “acks”).",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kafka_network_requestmetrics_totaltimems{quantile=\"0.95\", request=\"FetchFollower\"})"
    }
   ]
  }
 ]
}