{
 "title": "Strimzi / Kafka Fleet Panel",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Day 1 - Life Cycle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active alerts on Kafka clusters",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(ALERTS{namespace=\"^Kafka.*\"}) by (alertname, severity, namespace, cluster_id) * on (cluster_id) group_left () count(subscription_sync_total{installed=~\"^strimzi.*$\"}) by (cluster_id)"
    }
   ]
  },
  {
   "title": "Active alerts on openshift clusters",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count(ALERTS{namespace!=\"^Kafka.*\"}) by (alertname, severity, namespace, cluster_id) * on (cluster_id) group_left () count(subscription_sync_total{installed=~\"^strimzi.*$\"}) by (cluster_id)"
    }
   ]
  },
  {
   "title": "Kafka Cluster Compute Metrics",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\"}) by (namespace,cluster_id)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{container!=\"\",namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container != \"\", namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\"}) by (namespace)"
    },
    {
     "expr": "sum((sum(kubelet_volume_stats_available_bytes{ job=\"kubelet\", namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\"}) by (namespace) / sum(kubelet_volume_stats_capacity_bytes{ job=\"kubelet\", namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\"}) by (namespace) * 100)) by (namespace) "
    },
    {
     "expr": "sum(container_network_transmit_bytes_total{ container!= \"\",namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\"}) by (namespace)"
    },
    {
     "expr": "sum(container_network_receive_bytes_total{ container!= \"\",namespace !~\"openshift.*\", namespace !~\".*monitor.*\", namespace !~\".*operator.*\"}) by (namespace)"
    }
   ]
  },
  { "title": "Day 0 - Pre Install / Install", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total # of kafka clusters",
   "type": "singlestat",
   "description": "Total # of kafka clusters",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=~\"Kafka\"})"
    }
   ]
  },
  {
   "title": "Total # of kafka clusters failures",
   "type": "singlestat",
   "description": "Total # of kafka clusters failures",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum(strimzi_resources{kind=~\"Kafka\"}) by (kind) - ignoring(kind) sum(kafka_controller_kafkacontroller_active_controller_count)"
    }
   ]
  },
  {
   "title": "Srimzi operator versions",
   "type": "table",
   "description": "Srimzi operator versions",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 15 },
   "targets": [
    {
     "expr": "count(subscription_sync_total{installed=~\"^strimzi.*$\"}) by (installed)"
    }
   ]
  },
  {
   "title": "Total # of openshift clusters",
   "type": "table",
   "description": "Total # of openshift clusters",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 15 },
   "targets": [
    {
     "expr": "count((topk(1, subscription_sync_total{installed=~\"^strimzi.*$\"} > 0))) by (version) * on (instance) group_left(version) count(cluster_version{type=\"completed\"}) by (version)"
    }
   ]
  }
 ]
}