{
 "title": "Logs Dashboard",
 "description": "by Kind/namespace",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "kind", "query": "label_values(strimzi_io_kind)" },
   {
    "name": "cluster_id",
    "query": "label_values({strimzi_io_kind=~\"$kind\"},cluster_id) "
   },
   {
    "name": "namespace",
    "query": "label_values({cluster_id=~\"$cluster_id\"}, namespace)"
   },
   {
    "name": "container_name",
    "query": "label_values({namespace=~\"$namespace\"},container_name)"
   },
   {
    "name": "pods",
    "query": "label_values({container_name=~\"$container_name\"},statefulset_kubernetes_io_pod_name) "
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "search", "label": "search" }
  ]
 },
 "panels": [
  {
   "title": "log count by clusters",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time({cluster_id!=\"\"}  [1m])) by (cluster_id)"
    }
   ]
  },
  {
   "title": "log  counts for given selection",
   "type": "singlestat",
   "description": "Total Incoming Byte Rate",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time({strimzi_io_kind=~\"$kind\",namespace=~\"$namespace\",container_name=~\"$container_name\",statefulset_kubernetes_io_pod_name=~\"$pods\",cluster_id=~\"$cluster_id\"} [1m]))"
    }
   ]
  },
  {
   "title": "logs for given kind by namespace ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time({strimzi_io_kind =\"$kind\" } [1m]))by (namespace)"
    }
   ]
  },
  {
   "title": "Rate  for given kind by namespace",
   "type": "grafana-piechart-panel",
   "description": "Total Incoming Byte Rate",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate({strimzi_io_kind=~\"$kind\"} [1m])) by (namespace)"
    }
   ]
  },
  {
   "title": "Log count for selection  over time 30m by instance",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({strimzi_io_kind=~\"$kind\",namespace=~\"$namespace\",container_name=~\"$container_name\",statefulset_kubernetes_io_pod_name=~\"$pods\",cluster_id=~\"$cluster_id\"}  [1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Total count  over time 30m by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({strimzi_io_kind=~\"$kind\",namespace=~\"$namespace\",container_name=~\"$container_name\",statefulset_kubernetes_io_pod_name=~\"$pods\",cluster_id=~\"$cluster_id\"}  [1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Total rate over time 30m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({strimzi_io_kind=~\"$kind\",namespace=~\"$namespace\",container_name=~\"$container_name\",statefulset_kubernetes_io_pod_name=~\"$pods\",cluster_id=~\"$cluster_id\"} [1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Kafka Brokers Warning by namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({strimzi_io_kind=~\"$kind\",namespace=~\"$namespace\",container_name=~\"$container_name\",statefulset_kubernetes_io_pod_name=~\"$pods\",cluster_id=~\"$cluster_id\" ,app_kubernetes_io_name=\"kafka\"} |~ \"WARN | Warning\"  [1m]))  by (namespace)"
    }
   ]
  },
  {
   "title": "Kafka Brokers Error  by  namspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({strimzi_io_kind=~\"$kind\",namespace=~\"$namespace\",container_name=~\"$container_name\",statefulset_kubernetes_io_pod_name=~\"$pods\",cluster_id=~\"$cluster_id\" ,app_kubernetes_io_name=\"kafka\"} |= \"ERROR\"  [1m])) by (namespace)"
    }
   ]
  },
  {
   "title": "Zookeeper WARN by namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({strimzi_io_kind=~\"$kind\",namespace=~\"$namespace\",container_name=~\"$container_name\",statefulset_kubernetes_io_pod_name=~\"$pods\",cluster_id=~\"$cluster_id\" ,app_kubernetes_io_name=\"kafka\"}  |~ \"WARN | Warning\"  [1m])) by (namespace)"
    }
   ]
  },
  {
   "title": "Zookeeper Errors by namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({strimzi_io_kind=~\"$kind\",namespace=~\"$namespace\",container_name=~\"$container_name\",statefulset_kubernetes_io_pod_name=~\"$pods\",cluster_id=~\"$cluster_id\" ,app_kubernetes_io_name=\"kafka\"}  |~ \"ERROR\"  [1m])) by (tenant)"
    }
   ]
  },
  {
   "title": "Logs entries",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{strimzi_io_kind=~\"$kind\",namespace=~\"$namespace\",container_name=~\"$container_name\",statefulset_kubernetes_io_pod_name=~\"$pods\",cluster_id=~\"$cluster_id\"}|~ \"$search\" "
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", instance=~\"$pod\"} |~ \"$search\"[1m]))"
    }
   ]
  }
 ]
}