---
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
  namespace: openshift-logging
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    retentionPolicy:
      application:
        maxAge: 1d
      infra:
        maxAge: 1d
      audit:
        maxAge: 1d
    elasticsearch:
      nodeCount: 1
      nodeSelector:
        openshift-logging/storage: 'true'
      tolerations:
        - effect: NoSchedule
          key: openshift-logging/storage
          operator: Equal
          value: 'true'
      resources:
        limits:
          memory: 6Gi
        requests:
          cpu: 100m
          memory: 2Gi
      storage:
        storageClassName: "gp2"
        size: "60G"
      redundancyPolicy: "ZeroRedundancy"
  visualization:
    type: "kibana"
    kibana:
      nodeSelector:
        openshift-logging/storage: 'true'
      tolerations:
        - effect: NoSchedule
          key: openshift-logging/storage
          operator: Equal
          value: 'true'
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 1Gi
      replicas: 1
  curation:
    type: "curator"
    curator:
      nodeSelector:
        openshift-logging/storage: 'true'
      tolerations:
        - effect: NoSchedule
          key: openshift-logging/storage
          operator: Equal
          value: 'true'
      schedule: "* */3 * * *"
  collection:
    logs:
      type: "fluentd"
      fluentd:
        nodeSelector:
          openshift-logging/storage: 'true'
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 1Gi
