// begin header
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:numbered:
:toc: macro
:toc-title: pass:[<b>Table of Contents</b>]
// end header
= Sharded Ingress Controller for Managed Kafka

toc::[]

== Description

The purpose of this SOP is config an `ingresscontroller` for Managed Kafka.  This is done to direct Kafka traffic onto dedicated Ingress instances that
run on on the worker nodes.  This avoids overwhelming the default ingress instances which run on the infra nodes with high volumes of Kafka traffic.

== Prerequisites

1. The target OSD cluster exists.
1. Cluster credentials are held that allow the following operation:
   `oc auth can-i create ingresscontroller -n openshift-ingresscontroller`

== Execute/Resolution

1. Git clone this repo and `cd sops`
1. Login to the target cluster
1. Execute the following:

```
domain=$(oc get ingresscontroller -n openshift-ingress-operator default --output 'go-template={{.status.domain}}' | sed -e 's/^apps\./mk./')
oc process -f yamls/mk-ingresscontroller.yaml DOMAIN=${domain} REPLICAS=3 | oc apply -n openshift-ingress-operator -f -
```

== Validate

1. Run the following command and ensure that the ingresscontroller is reported as existing.

```oc get ingresscontroller -n openshift-ingress-operator mk-ingresscontroller```

== Troubleshooting

Provide any helpful troubleshooting information and/or links.
