// begin header
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:numbered:
:toc: macro
:toc-title: pass:[<b>Table of Contents</b>]
// end header
= Some SOP/Alert Name

toc::[]

== Description

The purpose of this SOP is to describe the process of resolving the alert someAlertName/define the process to foo a bar

The source of the alert is from the someAlertMetric metric, and fires when the condition has been met for more than 10 minutes/You may need to foo a bar if X, Y or Z

== Prerequisites

Any action or information which needs to be completed/known prior to beginning.

> Systems you will need access to, log collection that should be done prior to attempting any resolution, stakeholders which need to be notified prior to any action, etc.


== Execute/Resolution

Define, in a step-by-step fashion, how to do what needs to be done. 

> e.g., commands to be run, files to be changed, information to be captured etc.)

== Validate

What steps are required to verify that the procedure has been followed correctly and the required changes have been implemented correctly, with the desired outcome.

> e.g., have alerts resolved?, are dashboards as expected?, have services resumed?, etc.

== Troubleshooting

Provide any helpful troubleshooting information and/or links.