// begin header
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:numbered:
:toc: macro
:toc-title: pass:[<b>Table of Contents</b>]
// end header
= Updating the Observability Operator Image in Staging

toc::[]

== Description

This SOP outlines the process of rolling out a new Observability Operator image version to the OSD data plane staging cluster. As of writing, the staging image uses the tag `latest`.

== Prerequisites
1. The target OSD staging cluster exists. The `ID` of the target cluster can be obtained from the output of the following command:
+
[source,sh]
----
ocm list clusters
----
2. Admin access to the cluster. The credentials can be retrieved using the following command:
+
[source,sh]
----
ocm get /api/clusters_mgmt/v1/clusters/<cluster_id>/credentials
----

== Execute/Resolution
1. Build a new version of the Observability Operator image using the make target:
+
[source,sh]
----
make docker-build
----
2. By default, the image will be built using the `latest` tag. Verify that the image has the correct tag:
+
[source,sh]
----
docker images

REPOSITORY                                   TAG
quay.io/integreatly/observability-operator   latest
----
3. Push the newly created image to the quay.io `integreatly/observability-operator` repository:
+
[source,sh]
----
make docker/push
----
4. For the new image version to be pulled, the pods must be restarted. This can be achieved by restarting each of the deployments and statefulsets within the specified namespace:
+
[source,sh]
----
oc rollout restart deployment -n <namespace> && oc rollout restart statefulset -n <namespace>
----

== Validate
1. Check the status of each pod to ensure that all pods are running, and none are stuck in a pending/terminating or error state:
+
[source,sh]
----
oc get pods -n <namespace>
----
2. Some resources do not get updated when a new image is deployed. If the new image contains changes to any of the following resources, the resource must be updated manually in the cluster:

 Secrets
  - alertmanager-proxy
  - alertmanager-<alertmanager-name>
  - grafana-k8s-proxy
  - prometheus-proxy

 ConfigMap
  - promtaila-config

== Troubleshooting
None.